[2024-03-15T08:42:53.802+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: study_case1_restore.retrieve_data_and_save_to_csv manual__2024-03-15T08:42:52.489441+00:00 [queued]>
[2024-03-15T08:42:53.811+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: study_case1_restore.retrieve_data_and_save_to_csv manual__2024-03-15T08:42:52.489441+00:00 [queued]>
[2024-03-15T08:42:53.812+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-15T08:42:53.822+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): retrieve_data_and_save_to_csv> on 2024-03-15 08:42:52.489441+00:00
[2024-03-15T08:42:53.827+0000] {standard_task_runner.py:60} INFO - Started process 2402 to run task
[2024-03-15T08:42:53.830+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'study_case1_restore', 'retrieve_data_and_save_to_csv', 'manual__2024-03-15T08:42:52.489441+00:00', '--job-id', '292', '--raw', '--subdir', 'DAGS_FOLDER/restrore_mongo/study_case1_restore.py', '--cfg-path', '/tmp/tmpyfuyd9d1']
[2024-03-15T08:42:53.832+0000] {standard_task_runner.py:88} INFO - Job 292: Subtask retrieve_data_and_save_to_csv
[2024-03-15T08:42:53.868+0000] {task_command.py:423} INFO - Running <TaskInstance: study_case1_restore.retrieve_data_and_save_to_csv manual__2024-03-15T08:42:52.489441+00:00 [running]> on host f293363f8e27
[2024-03-15T08:42:53.934+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Agus mahari' AIRFLOW_CTX_DAG_ID='study_case1_restore' AIRFLOW_CTX_TASK_ID='retrieve_data_and_save_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T08:42:52.489441+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-15T08:42:52.489441+00:00'
[2024-03-15T08:42:53.936+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-03-15T08:42:56.465+0000] {logging_mixin.py:188} INFO -                         _id  id  ...   alamat         execution_at
1  65f407e0a3f12e69515dabfe   2  ...      NaN  2024-03-15 15:33:32
3  65f4058125246f4b275642a8   1  ...      NaN  2024-03-15 15:23:19
2  65f407e0a3f12e69515dabff   3  ...      NaN  2024-03-15 15:33:32
0  65f409b11fc2487feedd32c1   4  ...  cirebon  2024-03-15 15:41:18

[4 rows x 8 columns]
[2024-03-15T08:42:56.468+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-03-15T08:42:56.478+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=study_case1_restore, task_id=retrieve_data_and_save_to_csv, execution_date=20240315T084252, start_date=20240315T084253, end_date=20240315T084256
[2024-03-15T08:42:56.510+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-15T08:42:56.532+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
