[2024-03-12T09:39:51.276+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_lima_solid.load_to_mongodb_task manual__2024-03-12T09:39:45.686674+00:00 [queued]>
[2024-03-12T09:39:51.288+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_lima_solid.load_to_mongodb_task manual__2024-03-12T09:39:45.686674+00:00 [queued]>
[2024-03-12T09:39:51.288+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-12T09:39:51.301+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): load_to_mongodb_task> on 2024-03-12 09:39:45.686674+00:00
[2024-03-12T09:39:51.305+0000] {standard_task_runner.py:60} INFO - Started process 181 to run task
[2024-03-12T09:39:51.308+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'example_lima_solid', 'load_to_mongodb_task', 'manual__2024-03-12T09:39:45.686674+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/other_ingestion_postgre/main_dag_sql_lima.py', '--cfg-path', '/tmp/tmpv6k1f0m7']
[2024-03-12T09:39:51.310+0000] {standard_task_runner.py:88} INFO - Job 21: Subtask load_to_mongodb_task
[2024-03-12T09:39:51.348+0000] {task_command.py:423} INFO - Running <TaskInstance: example_lima_solid.load_to_mongodb_task manual__2024-03-12T09:39:45.686674+00:00 [running]> on host 31e68e31498e
[2024-03-12T09:39:51.415+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_lima_solid' AIRFLOW_CTX_TASK_ID='load_to_mongodb_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-12T09:39:45.686674+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-12T09:39:45.686674+00:00'
[2024-03-12T09:39:51.417+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-03-12T09:39:54.032+0000] {logging_mixin.py:188} INFO - An error occurred: [Errno 2] No such file or directory: '/opt/***/data/aplikasi_table_2024-03-12-9-39-45.csv'
[2024-03-12T09:39:54.032+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-03-12T09:39:54.041+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=example_lima_solid, task_id=load_to_mongodb_task, execution_date=20240312T093945, start_date=20240312T093951, end_date=20240312T093954
[2024-03-12T09:39:54.070+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-12T09:39:54.088+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
